ad/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('admin', views.login_form),
    path('admin/login', views.login),
    path('admin/logout', views.logout),
    path('admin/index', views.index),
    path('admin/changepassword_form', views.change_password_form),
    path('admin/changepassword', views.changepwd),
    path('admin/category', views.category),
    path('admin/category/edit', views.category_edit),
    path('admin/category/update=<int:id>', views.category_update),
    path('admin/category/delete=<int:id>', views.delete_category),
    path('admin/category/attributes_attrgroups', views.attributes_attrgroups),
    path('admin/attribute_groups', views.attribute_groups),
    path('admin/attribute_groups/delete=<int:id>', views.delete_attribute_groups),
    path('admin/attribute_groups/update=<int:id>', views.update_attribute_groups),
    path('admin/attributes', views.attributes),
    path('admin/all_account', views.all_account),
    path('admin/blocked_account', views.blocked_account),
    path('admin/unblock_account', views.unblock_account),
    path('admin/attributes/delete=<int:id>', views.delete_attributes),
    path('admin/attributes/update=<int:id>', views.update_attributes),
    path('admin/message', views.message),
    path('admin/message/room_id/<str:room_id>', views.message_inner),
    path('admin/room', views.room),
    path('admin/room/history_bidding/<str:room_id>', views.room_history),
    #huy gia
    path('admin/cancel/bid', views.find_cancel_bid_form),
    #load product
    path('admin/cancel/bid/load/product', views.load_product),
    #load reason_form
    path('admin/cancel/bid/load/reason_form/<str:room_id>', views.reason_form),
    #load confirm
    path('admin/cancel/bid/load/confirm/<str:room_id>/<str:bidder>', views.confirm_form),
    #cancel bid
    path('admin/cancel_bid', views.cancel_bid),
    ]

auction_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path('', include('website.urls')),
    path('', include('ad.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ad/models.py
# https://github.com/MongoEngine/django-mongoengine
from mongoengine import *
from django_mongoengine import fields, Document
import datetime
# Create your models here.

class auction_account(Document):
    account = fields.StringField(max_length=100)
    password = fields.StringField(max_length=100)

class account(Document):
    id = fields.StringField(max_length=100, primary_key=True)
    password = fields.StringField(max_length=100)
    email = fields.StringField(max_length=100)
    phonenb = fields.StringField(max_length=100, blank=True)
    address = fields.StringField(max_length=100, blank=True)
    city = fields.StringField(max_length=300, blank=True)
    district = fields.StringField(max_length=300, blank=True)
    role = fields.StringField(max_length=100, blank=True)
    img_url = fields.StringField(default=None, blank=True)
    status = fields.StringField(default='active')
    nb_bidcancel = fields.IntField(default=0)


class attribute_groups(Document):
    id = fields.IntField(primary_key=True)
    name = fields.StringField(max_length=300)

class attributes(Document):
    attr_groups_list = []
    for c in attribute_groups.objects:
        attr_groups = (str(c.id), c.name)
        attr_groups_list.append(attr_groups)
    id = fields.IntField(primary_key=True)
    name = fields.StringField(max_length=300)
    # attribute_groups_id = fields.IntField(choices=attr_groups_list)
    # atrg is refe..field in model so it just saves _id of corresponding attribute_groups documenent. (see attributes in view)
    attribute_groups_id = fields.ReferenceField('attribute_groups',reverse_delete_rule=CASCADE)

class category(Document):
    id = fields.IntField(primary_key=True)
    category_parent = fields.IntField()
    name = fields.StringField(max_length=300)
    attributes_id = fields.ListField(ReferenceField('attributes', reverse_delete_rule=CASCADE), blank=True)


class chat_room(Document):
    host = fields.ReferenceField('account',reverse_delete_rule=CASCADE)
    user = fields.ReferenceField('account',reverse_delete_rule=CASCADE)

class messages(Document):
    chat_room = fields.ReferenceField('chat_room',reverse_delete_rule=CASCADE)
    sender = fields.ReferenceField('account',reverse_delete_rule=CASCADE)
    receiver = fields.ReferenceField('account',reverse_delete_rule=CASCADE)
    content = fields.StringField()
    time = fields.DateTimeField(default=datetime.datetime.utcnow)
    status = fields.StringField(default='received')

ad/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.forms import DeclarativeFieldsMetaclass
from django.forms.models import ALL_FIELDS
from .models import *
from  . import models
from django_mongoengine.forms import DocumentForm
from django_mongoengine import fields

# class SignupForm(forms.Form):
#    account  = forms.CharField(label='Tên đăng nhập', max_length=100)
#    password = forms.CharField(max_length=100)
#    auth_password = forms.CharField(max_length=100)
#    email = forms.CharField(max_length=100)
#    auth_email = forms.CharField(max_length=100)

# 111
class AccountForm(forms.Form):
   account  = forms.CharField(label='Tài khoản', max_length=100)
   password = forms.CharField(label='Mật khẩu',
                              widget=forms.PasswordInput(attrs={'id':'password',
                              'placeholder': '****', 'title':"Vui lòng nhập mật khẩu"}))

   account.widget.attrs.update({'id':'username', 'placeholder': 'admin','title':"Vui lòng nhập tên đăng nhập"})

   def __init__(self, *args, **kwargs):
      super(AccountForm, self).__init__(*args, **kwargs)
      for visible in self.visible_fields():
         visible.field.widget.attrs['class'] = 'form-control'

class ChangePaswordForm(forms.Form):
   OldPassword  = forms.CharField(label='Mật khẩu cũ',
                              widget=forms.PasswordInput(attrs={'id': 'OldPwd',
                              'placeholder': '****', 'title':"Vui lòng nhập mật khẩu hiện tại"}))
   NewPassword = forms.CharField(label='Mật khẩu mới',
                              widget=forms.PasswordInput(attrs={'id':'NewPwd',
                              'placeholder': '****', 'title':"Vui lòng nhập mật khẩu mới"}))

   AuthPassword = forms.CharField(label='Xác nhận mật khẩu',
                                 widget=forms.PasswordInput(attrs={'id': 'AuthPwd',
                                                                   'placeholder': '****',
                                                                   'title': "Vui lòng nhập xác nhận mật khẩu mới"}))

   def __init__(self, *args, **kwargs):
      super(ChangePaswordForm, self).__init__(*args, **kwargs)
      for visible in self.visible_fields():
         visible.field.widget.attrs['class'] = 'form-control'




def get_values():
    list = []
    category_list = [(0,'---Chọn---')]

    for cate in models.category.objects:
        if cate.attributes_id == [] or cate.attributes_id[0].id == 0:
            list1 = [cate.name]
            pr = cate.category_parent

            while pr != 0:
                if pr != 0:
                    c = models.category.objects.get(id=pr)
                    pr = c.category_parent
                    list1.append(c.name)
            list1.reverse()
            s = ' > '.join([str(item) for item in list1])
            list.append({'id': cate.id, 'name': s})

    for l in list:
        item = (l['id'], l['name'])
        category_list.append(item)

    return category_list

def get_list():
    ls = [(0,'---Chọn---')]
    for a in models.attributes.objects:
        item = (a['id'], a['name'])
        ls.append(item)
    return ls

class CategoryForm(DocumentForm):
    id = forms.CharField(label='Mã danh mục')
    category_parent = forms.ChoiceField(label='Danh mục cha', choices=get_values, initial=0)
    name = forms.CharField(label='Tên danh mục', max_length=100)
    # attributes_id = forms.ChoiceField(label='Tên thuộc tính', choices=attributes.objects.values_list('id','name'))
    attributes_id = forms.ChoiceField(label='Tên thuộc tính', choices=get_list, initial=0)

    def __init__(self, *args, **kwargs):
      super(CategoryForm, self).__init__(*args, **kwargs)
      self.fields['attributes_id'].widget.attrs.update({'style': 'width: 100%;'})
      for visible in self.visible_fields():
         visible.field.widget.attrs['class'] = 'form-control'

      # self.fields['category_parent'] = forms.ChoiceField(label='Danh mục cha', choices=category_list, initial='')
      self.fields['attributes_id'].widget.attrs.update({'class': 'form-control tt'})

    class Meta:
      document = models.category
      fields = ('__all__')


class AttributeGroupsForm(DocumentForm):
    name = forms.CharField(label='Tên nhóm thuộc tính', max_length=300, required=True)
    name.widget.attrs['name'] = 'name'
    def __init__(self, *args, **kwargs):
      super(AttributeGroupsForm, self).__init__(*args, **kwargs)
      for visible in self.visible_fields():
         visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
      document = attribute_groups
      fields = ('__all__')


def get_list_attr_group():
    l = [(0, '---Chọn---')]
    for a in models.attribute_groups.objects:
        item = (a['id'], a['name'])
        l.append(item)
    return l

class AttributesForm(DocumentForm):
    # attr_groups_list = []
    # for c in attribute_groups.objects:
    #     attr_groups = (c.id, c.name)
    #     attr_groups_list.append(attr_groups)


    name = forms.CharField(label='Tên thuộc tính', max_length=300)
    name.widget.attrs['name'] = 'name'
    attribute_groups_id = forms.ChoiceField(label='Nhóm thuộc tính',
                                            choices=get_list_attr_group, initial=0)
    # attribute_groups_id = forms.ChoiceField(label='Nhóm thuộc tính',choices=attribute_groups.objects.values_list('id','name'))

    def __init__(self, *args, **kwargs):
      super(AttributesForm, self).__init__(*args, **kwargs)
      for visible in self.visible_fields():
         visible.field.widget.attrs['class'] = 'form-control'

      self.fields['attribute_groups_id'].widget.attrs['class'] = 'form-control t'

    class Meta:
      document = attributes
      fields = ('__all__')
      # fields = ['id', 'name'] #attribute_groups_id will be handled in view

templates/ad/attributes.html
{% extends "ad/base.html" %}
{% block title %}
    <title>Thuộc tính</title>
{% endblock %}

{% block breadcome-area %}
{% endblock %}

{% block content %}
        <div class="product-status mg-b-15" style="padding-top: 100px;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>
<!--                                <i class="fa fa-pencil" aria-hidden="true"></i>-->
                                Thuộc tính</h4>
                            <div class="add-product">
<!--                                <a href="#">Thêm</a>-->
                            </div>
                            <div class="asset-inner">
                                <table id="mytable">
                                    <tr>
                                        <th>STT</th>
                                        <th>{{ form.name.label }}</th>
                                        <th>{{ form.attribute_groups_id.label }}</th>
                                        <th>Thao tác</th>
                                    </tr>
                                    {% for c in attributes %}
                                  <form method="post">
                                    {% csrf_token %}
                                    <tr>
                                        <td class="id">{{ forloop.counter|add:0 }}
                                            <input type="hidden" class="Id" value="{{ c.id }}">
                                        </td>
                                        <td class="name">{{ c.name }}</td>
                                        <td>{{ c.attribute_groups_id.name }}
                                            <input type="hidden" class="attribute_groups_Id" value="{{ c.attribute_groups_id.id }}">
                                        </td>
                                        <td>
                                            <button data-toggle="tooltip" title="Sửa" class="pd-setting-ed edit-btn"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Xóa" class="pd-setting-ed delete-btn"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                  </form>
                                  <form method="post">
                                    {% csrf_token %}
                                    <tr class="vd">
                                        <td id="form_id" class="id"> </td>
                                        <td>{{ form.name }}</td>
                                        <td id="form_attg" >{{ form.attribute_groups_id }}</td>
                                        <td>
                                            <button data-toggle="tooltip" type="submit" title="Thêm" class="pd-setting-ed add-form"><i class="fa fa-plus" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                  </form>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<!--        <div class="footer-copyright-area">-->
<!--            <div class="container-fluid">-->
<!--                <div class="row">-->
<!--                    <div class="col-lg-12">-->
<!--                        <div class="footer-copy-right">-->
<!--                            <p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
{% endblock %}

<!--Modal-->
{% block modal-title %}<i class="fa fa-pencil" aria-hidden="true"></i> Cập nhật {% endblock %}
{% block modal-content %}
  <form method="post">
   {% csrf_token %}
   <div class="modal-body">
       <div class="form-group p_name p_Id">
             <label class="control-label">{{ form.name.label }}</label>
             <input type="hidden" class="Id">
             {{ form.name }}
       </div>
       <div class="form-group">
           <label class="control-label">{{ form.attribute_groups_id.label }}</label>
           {{ form.attribute_groups_id }}
       </div>
   </div>
   <div class="modal-footer">
       <button type="button" type="submit" class="btn btn-default edit" data-dismiss="modal">Đồng ý</button>
   </div>
  </form>
{% endblock %}
<!--End-Modal-->

{% block javascript %}
<script>
    $(document).on('click','.add-form', function someFunction(e){
       e.preventDefault();
       var len = $('#mytable tr').length - 2;
       var $tr = $("#mytable tr:eq("+len+")");
       var $id = $tr.find(".id");
       if ($id[0]){
          var id_nb = parseInt($id.html()) + 1;
       }
       else {
          var id_nb = 1;
       }
       var $name = $("#id_name");
       var $attribute_groups_id = $("#id_attribute_groups_id").find(":selected").val();
<!--       alert($("#id_attribute_groups_id").find(":selected").text());-->
       $.ajax({
               type: 'POST',
               url: "/admin/attributes",
               data: {
                  csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                  id: id_nb,
                  name: $name.val(),
                  attribute_groups_id: parseInt($attribute_groups_id)
               },
               success: function (response) {
                  if(response['message'] == '') {
                       $("#mytable").load("/admin/attributes #mytable");
                     }
                  else {
                     alert(response['message']);
                  }
               },
               error: function (response) {
                  console.log(response)
               }
         });
     });
</script>
<script>
    $(document).on('click','.delete-btn', function someFunction(e){
       e.preventDefault();
       var result = confirm("Bạn có chắc muốn xóa Thuộc tính này không?");
       if (result) {
       var $td = $(this).parent();
       var $tr = $td.parent();
       var $id = $tr.find(".Id");
       $.ajax({
               type: 'POST',
               url: "/admin/attributes/delete=" + $id.val(),
               success: function (response) {
                   $("#mytable").load("/admin/attributes #mytable");
                   alert('Xóa thành công!');
               },
               error: function (response) {
                  console.log(response)
               }
         });
        }
     });
</script>
<script>
    $(document).on('click','.edit-btn', function someFunction(e){
       e.preventDefault();
       var $td = $(this).parent();
       var $tr = $td.parent();
       var $name = $tr.find(".name");
       var $id = $tr.find(".Id");
       var $attribute_groups_id = $tr.find(".attribute_groups_Id");
       $(".p_name #id_name").val($name.html());
       $(".p_Id .Id").val($id.val());
       $(".form-group #id_attribute_groups_id").val($attribute_groups_id.val());
       $('#myModal').addClass('show');
    });
</script>
<script>
    $(document).on('click','.edit', function someFunction(e){
       e.preventDefault();
       $.ajax({
               type: 'POST',
               url: "/admin/attributes/update=" + $(".p_Id .Id").val(),
               data: {
                  csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                  id: $(".p_Id .Id").val(),
                  name: $(".p_name #id_name").val(),
                  attribute_groups_id: $(".form-group #id_attribute_groups_id").val()
               },
               success: function (response) {
                  if (response['message'] == '') {
                   alert('Cập nhật thành công!');
                   $('#myModal').removeClass('show');
                   $("#mytable").load("/admin/attributes #mytable");
                   }
                   else {
                      alert(response['message']);
                   }
               },
               error: function (response) {
                  console.log(response)
               }
         });
    });
</script>
{% endblock %}

templates/ad/category_update.html
{% extends "ad/category_edit.html" %}
{% load static %}
{% block title %}
    <title>Cập nhật danh mục</title>
{% endblock %}
{% block stylesheet%}
   <!-- chosen CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'admin/css/chosen/bootstrap-chosen.css' %}">
{% endblock %}
{% block 'bl' %}
    <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                <div id="dropzone1" class="pro-ad addcoursepro">
                                                    <form method="post" id="update_form" class="dropzone dropzone-custom needsclick addlibrary">
                                                        {% csrf_token %}
                                                        <div class="row">
                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                <div class="form-group">
                                                                    <label class="control-label">{{ form.category_parent.label }}</label>
																    {{ form.category_parent }}
                                                                    <input type="hidden" id="cate_parent" value="{{ cate.category_parent }}">
															    </div>
                                                                <div class="form-group">
                                                                    <label class="control-label">{{ form.name.label }}</label>
                                                                    {{ form.name }}
                                                                    <input type="hidden" id="cate_name" value="{{ cate.name }}">
                                                                    <input type="hidden" id="cate_id" value="{{ cate.id }}">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="product-tab-list tab-pane fade" id="reviews">
                                    <div class="row">
                                        <div class="add-product" style="float: right;">
                                            <button data-toggle="tooltip" title="Thêm" class="pd-setting-ed add-attr-btn"><i class="fa fa-plus" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Lưu" class="pd-setting-ed save-attr-btn"><i class="fa fa-save" aria-hidden="true"></i></button>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            <h4>{{ form_attribute.attribute_groups_id.label }}</h4>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            <h4 class="control-label">{{ form_attribute.name.label }}</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row" id="attr-form">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                {% if cate.attributes_id.0.id is None %}
<!--                                                Danh mục không có thuộc tính.-->
                                                <div class="row attr-form check" style="display: none;">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                           {{ form_attribute.attribute_groups_id }}
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                                        <div class="form-group">
                                                            {{ form.attributes_id }}
                                                            <input type="hidden" class="cate_attr_id" value="0">
                                                            <input type="hidden" class="cate_attr_gr_id" value="0">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">
                                                        <div class="form-group">
                                                            <button data-toggle="tooltip" title="Xóa" class="pd-setting-ed remove-attr-btn"><i class="fa fa-remove" aria-hidden="true"></i></button>
                                                        </div>
                                                    </div>
                                                </div>
                                                {% elif cate.attributes_id.0.id is not None %}
                                                {% for c in cate.attributes_id %}
                                                <div class="row attr-form check">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                           {{ form_attribute.attribute_groups_id }}
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                                        <div class="form-group">
                                                            {{ form.attributes_id }}
                                                            <input type="hidden" class="cate_attr_id" value="{{ c.id}}">
                                                            <input type="hidden" class="cate_attr_gr_id" value="{{ c.attribute_groups_id.id}}">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">
                                                        <div class="form-group">
                                                            <button data-toggle="tooltip" title="Xóa" class="pd-setting-ed remove-attr-btn"><i class="fa fa-remove" aria-hidden="true"></i></button>
                                                        </div>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
    </div>
{% endblock %}

{% block save-btn %}
<script src="{% static 'admin/js/dropzone/dropzone.js' %}"></script>
<!-- chosen JS
		============================================ -->
    <script src="{% static 'admin/js/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'admin/js/chosen/chosen-active.js' %}"></script>
<!--    &lt;!&ndash; Select2 CSS &ndash;&gt;-->
<!--<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />-->

<!-- jQuery --> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!--&lt;!&ndash; Select2 JS &ndash;&gt;-->
<!--<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>-->

<script>
    $(document).ready(function(){
        $(".t").attr('disabled', 'disabled');
        $("#id_name").val($("#cate_name").val());
        $("#id_category_parent").val($("#cate_parent").val());
        var attributes_id = $(".cate_attr_id");
        var attributes_gr_id = $(".cate_attr_gr_id");
        var select_att = $(".tt");
        var select_gr = $(".t");
        for (i = 0; i < attributes_id.length; i++) {
          select_att.eq(i).val(attributes_id.eq(i).val()).change();
          select_gr.eq(i).val(attributes_gr_id.eq(i).val()).change();
       }
       $("#id_category_parent").attr('disabled', 'disabled');
    });
</script>
<script>
     $(document).on('click','.save-attr-btn', function someFunction(e){
       e.preventDefault();
       values = [];
       var select = document.getElementsByClassName("form-control tt");
       for (let i = 0; i < select.length; i++) {
              values.push(select[i].value);
       }
       var check = 'False';
       if ($(".check").css('display') != 'none'){
          check = 'True';
       }
       $.ajax({
               type: 'POST',
               url: "/admin/category/update=" + $("#cate_id").val(),
               data: {
                  csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                  id: 1,
                  category_parent: $("#id_category_parent").val(),
                  name: $("#id_name").val(),
                  check_add_attr: check,
                  attributes: values,
                  attributes_id: 0,
               },
               success: function (response) {
                  if(response['message'] == '') {
                       alert('Cập nhật thành công!');
                       $("#edit_form").load("/admin/category/update #update_form");
                  }
                  else {
                     alert(response['message']);
                  }
               },
               error: function (response) {
                  console.log(response)
               }
       });
     });
    </script>
{% endblock %}